INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (2, 'The Magician', '의지, 창의성, 자원 활용');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (3, 'The High Priestess', '직관, 무의식, 신비');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (4, 'The Empress', '풍요, 모성, 창조');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (5, 'The Emperor', '권위, 통제, 안정');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (6, 'The Hierophant', '전통, 사회적 규범, 영적 지도');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (7, 'The Lovers', '사랑, 조화, 관계의 선택');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (8, 'The Chariot', '승리, 의지력, 성공');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (9, 'Strength', '용기, 자제력, 인내');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (10, 'The Hermit', '고독, 자기 성찰, 지혜');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (11, 'Wheel of Fortune', '변화, 운명, 행운');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (12, 'Justice', '정의, 균형, 진실');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (13, 'The Hanged Man', '희생, 새로운 관점, 중립적인 태도');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (14, 'Death', '변화, 끝, 새로운 시작');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (15, 'Temperance', '균형, 조화, 절제');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (16, 'The Devil', '유혹, 물질주의, 속박');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (17, 'The Tower', '갑작스러운 변화, 붕괴, 충격');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (18, 'The Star', '희망, 영감, 재생');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (19, 'The Moon', '환상, 무의식, 불안');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (20, 'The Sun', '성공, 기쁨, 긍정적인 에너지');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (21, 'Judgment', '부활, 내적 각성, 평가');
INSERT INTO Tarots (tarot_Id, tarot_Name, tarot_Meaning) VALUES (22, 'The World', '완성, 성취, 통합');