name: Java CI with Gradle

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t dreamhigh .
          docker tag dreamhigh parkyeeyeon/dreamhigh:${GITHUB_SHA::7}
          docker push parkyeeyeon/dreamhigh:${GITHUB_SHA::7}

      # AWS credentials configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to Server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          aws ssm send-command \
            --instance-ids i-0352da18b718c5bfc \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands": [
              "if sudo docker ps -a --format \'{{.Names}}\' | grep -q \'^server$\'; then",
              "  sudo docker stop server",
              "  sudo docker rm server",
              "fi",
              "sudo docker pull parkyeeyeon/dreamhigh:${GITHUB_SHA::7}",
              "sudo docker tag parkyeeyeon/dreamhigh:${GITHUB_SHA::7} dreamhigh",
              "sudo docker run -d --name server -p 8080:8080 \\",
              "-e AWS_RDS_URL=${AWS_RDS_URL} \\",
              "-e AWS_RDS_USERNAME=${AWS_RDS_USERNAME} \\",
              "-e AWS_RDS_PASSWORD=${AWS_RDS_PASSWORD} \\",
              "-e G_CLIENT_ID=${G_CLIENT_ID} \\",
              "-e G_CLIENT_SECRET=${G_CLIENT_SECRET} \\",
              "-e MAIL_USERNAME=${MAIL_USERNAME} \\",
              "-e MAIL_PASSWORD=${MAIL_PASSWORD} \\",
              "-e APP_KEY=${APP_KEY} \\",
              "-e APP_URL=${APP_URL} \\",
              "-e JWT_KEY=${JWT_KEY} \\",
              "dreamhigh"
            ]}' \
            --output text
